MODULE_DEPENDENCIES = {
    "CAD": [],
    "EPCR": ["CAD"],
    "BILLING": ["EPCR"],
    "FIRE": [],
    "TELEHEALTH": [],
    "HEMS": ["COMMS"],
    "COMMS": [],
    "EMAIL": ["COMMS", "DOCUMENT_STUDIO"],
    "SCHEDULING": [],
    "INVENTORY": [],
    "AUTOMATION": [],
    "VALIDATION": [],
    "COMPLIANCE": [],
    "AI_CONSOLE": [],
    "FOUNDER": [],
    "INVESTOR": [],
    "EVENTS": [],
    "BUSINESS_OPS": [],
    "TRAINING": [],
    "EXPORTS": [],
    "REPAIR": [],
    "DOCUMENT_STUDIO": ["EXPORTS", "VALIDATION"],
    "WORKFLOWS": [],
    "BUILDERS": ["VALIDATION", "WORKFLOWS"],
    "SEARCH": [],
    "JOBS": [],
    "ANALYTICS": [],
    "FEATURE_FLAGS": [],
    "QA": ["COMPLIANCE", "EPCR"],
    "NARCOTICS": ["INVENTORY"],
    "MEDICATION": ["EPCR", "NARCOTICS"],
    "INVENTORY": [],
    "FLEET": ["INVENTORY"],
    "LEGAL_PORTAL": ["COMPLIANCE"],
    "PATIENT_PORTAL": ["BILLING"],
}

MODULE_KEYS = list(MODULE_DEPENDENCIES.keys())
